project:
  type: website
  output-dir: docs

website:
  title: "Gatins Lab Protocols"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Welcome
#      - about.qmd
#      - people.qmd
#      - text: "Welcome"
#        file: welcome.qmd
      - text: "Lab Protocols"
        file: lab_generalprotocols.qmd
      - text: "Field Protocols"
        file: fieldprotocols.qmd
      - text: "Professional Development"
        file: prof_development.qmd
      - text: "Coding"
        file: coding.qmd

    right:
      - icon: github
        href: https://github.com/remygatins
      - icon: twitter 
        href: https://twitter.com/remygatins?lang=en
        
  sidebar:
    - title: "Welcome"
      logo: pictures/Gatins_Lab_logo_dark_simple.png
      style: "docked"
      background: light
      collapse-level: 1
      contents:
        - section: "Welcome"
          contents: 
            - index.qmd
#           - welcome.qmd
            - welcome_onboarding.qmd
            - welcome_google_drive.qmd
            - welcome_lab_exit.qmd
            
    - title: "Lab Protocols"
      logo: pictures/Gatins_Lab_logo_dark_simple.png
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "General Protocols"
          contents: 
            - lab_generalprotocols.qmd
            - lab_gen_sharedlabspace.qmd
            - lab_gen_pipetting.qmd
            - lab_gen_water.qmd
            - lab_gen_stableisotope.qmd
        - section: "Equipment"
          contents:
            - lab_equip_80_freezer.qmd
            - lab_equip_autoclave.qmd
            - lab_equip_tapestation.qmd
            - lab_equip_qubit.qmd
            - lab_equip_ph_meter.qmd
        - section: "Molecular Protocols"
          contents:
            - lab_molec_etoh.qmd
            - section: "eDNA Protocols"
              contents:
                - lab_molec_eDNA_filtration.qmd
                - lab_molec_eDNA_extraction.qmd
                - lab_molec_eDNA_qpcr.qmd
            - lab_molec_dnaextraction.qmd
            - lab_molec_DNA_beadcleanup.qmd
            - section: "Illumina WGS Library Prep"
              contents:
                - lab_molec_illuminalibraryprep.qmd
                - lab_molec_yinlineannealing.qmd
            - lab_molec_gel_electrophoresis.qmd
            - lab_molec_low_te_buffer.qmd
            
    
    - title: "Field Protocols"
      logo: pictures/Gatins_Lab_logo_dark_simple.png
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Fieldwork general"
          contents:
            - fieldprotocols.qmd
            - field_finclips.qmd
            - lab_molec_eDNA_filtration.qmd
        - section: "Permits"
          contents:
            - field_permits_US.qmd
            - field_permits_Panama.qmd
        - section: "Diving"
          contents: 
            - field_diving_general.qmd

    - title: "Professional Development"
      logo: pictures/Gatins_Lab_logo_dark_simple.png
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - section: "Professional Development"
          contents:
            - prof_development.qmd
            - prof_dev_job_boards.qmd

    - title: "Coding"
      logo: pictures/Gatins_Lab_logo_dark_simple.png
      style: "floating"
      background: light
      collapse-level: 1
      contents:
        - coding.qmd
        - section: "Maps"
          contents:
            - coding_map_stamen_ggmap.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
