# Synology NAS

Quick Guide to access the Gatins Lab Synology NAS system.

**NAS** is a **Network-attached-storage** system that is connected to our lab computer (similar to an external hard drive), however, it acts as its own computer. It is easy to extend the memory on it by simply adding new hard drives but thinks of them all as just one large hard drive. We will use it to store backup data for all our projects and for lab member to store their data before leaving the lab. 

## Connect to Gatins Lab Synology system

You first need to be added as a user from the admin account. Let Remy know if you want to be added. Once you are added, you will get an email to your personal email asking you to set up your new password. Your username will be the same as your Northeastern username. 

**Option 1: Create a folder in finder**  
*Preferred option*

On a MAC:  

1. First connect to the NU VPN (if you are off campus)  
2. In your tool bar go the "Go" tab and hit "Connect to server"  
3. copy and paste the following address "smb://129.10.11.41" and hit "connect"  
4. sign in with your username and password  
5. Open "Finder" and navigate down to "Locations" on the left toolbar   
6. Within "Network" you should see our GatinsLab Synology under the IP "129.10.11.41"  
7. Navigate within that volume to access the files and use it as any other folder on your computer. 
  - e.g., you can change directory in the command line to that directory and source copy any file from the explorer cluser into it.


**Option 2: QuickConnect**  
Gives you access through the web browser to the synology NAS platform

1. Go to <https://quickconnect.to/gatins>
2. Sign in with your username and password
3. Access our shared lab files through the "File Manager" or "Synology DiskDrive"


## File Structure

Within our GatinsLab Synology there are two main shared folders: 

* Lab_Resources
* Projects

Within the "Projects" folder, you should create a folder for each one of your projects using the following syntax: **YYYY_ProjectName_YourInitials** (e.g., 2024_BSB_RangeWide_RG).  

If you have multiple projects (e.g., one for each of your dissertation chapters), make a folder for each project. 

Within your project folder, create the following subfolders and files:

* Raw Data (folder and put any raw data obtained directly from any sequencing facility)  
* Explorer (any files, analyses and scripts you have on the explorer cluster)  
  - src  
  - data  
  - results  
* Documents (within this folder you can have more subfolders but put any relevant documents of the project here)  
* Metadata (please upload any metadata associated with the project)  
* Readme.txt (make a readme file briefly stating what the project was about and list any links to external repositories such as GoogleDrive, Github, etc)  


