# Scientific Permitting in Panama
[Edit this page](https://github.com/remygatins/GatinsLabProtocols/edit/main/field_permits_Panama.qmd)

If you are traveling to Panama for fieldwork, you will need permits to (1) collect and (2) export your samples. If you will be working with the Smithsonian Tropical Research Institute, they are extremely helpful and have a whole web page with resources for obtaining these permits [here](https://stri.si.edu/plan-your-visit/scientific-research-permits). For work in our lab, permits will likely be issued by the Ministry of Environment (MiAmbiente).

## 1. Collection Permits
If you are requesting new permits, begin this process EARLY -- as in at least 3-4 months in advance. The STRI webpage linked [here](https://stri.si.edu/plan-your-visit/scientific-research-permits/miambiente-request-permit) contains information on required materials for your application.

** NOTE:** All collaborators will be required to send the following documents:
- [ ] Copy of passport
- [ ] Signed Release of Responsibility
- [ ] 1-page CV in Spanish
So if you are just joining someone's existing permit, you will still be required to submit these documents. 

It costs $25 to amend an existing collection permit.

## 2. Export Permits
Export permits take ~2 months to be approved. Follow [this page](https://stri.si.edu/plan-your-visit/scientific-research-permits/miambiente-export-permit) to ensure you follow all the steps required for a successful export permit application. The required paperwork includes the following completed *in Spanish*:
- [ ] Ministerio de Ambiente Export Permit Form
- [ ] Collecting Report form
- [ ] Material Transfer Agreement
- [ ] Specimen Deposit Letter (Carta Remisoria)

Follow [this link](https://drive.google.com/drive/folders/1wE9jIndYUp7XswdRHDRRJKcNkoObmN4v?usp=drive_link) to view Annabel's completed and approved export permit application materials. 

** NOTE:** The Carta Remisoria is meant to ensure all marine and fresh water specimens collected within Panama are deposited to the University of Panama Marine Biology and Limnology Museum. One samples of each species collected should be deposited to the museum. Recently, the collection has grown and samples are not always requested to be dropped off, but it is important to contact Professor Edgardo Muñoz ahead of time to be sure.
