# US Field Permits

## Florida
For questions regarding which permits are appropriate for your specific activities, contact the **Florida Fish and Wildlife Conservation Commission Marine Fisheries Management** department at **850-487-0554**.

# Recreational Fishing Licenses
Recreational fishing (via pole or spear) is quite simple in Florida. [Here](https://myfwc.com/license/recreational/saltwater-fishing/) is the page for Recreational Saltwater Licenses & Permits and [here](https://myfwc.com/fishing/saltwater/recreational/spearing/) is the page with specific information regarding spearing.

# Special Activity Licenses
A [Special Activity License (SAL)](https://myfwc.com/license/saltwater/special-activity-licenses/) is required if collection plans exceed marine fisheries regulations. In order to collect *Holacanthus*, a SAL is required because families of ornamental reef fish such as angelfish are on the prohibited species harvest list (see Spearing page for details).

There are a few different types of SALs, but we will be submitting a [Scientific Research SAL](https://myfwc.com/media/1193/sal-scientificresearch.pdf). 

** *Will continue updating after we hear back about our application! - Annabel 03/14/2024*

# Florida Keys National Marine Sanctuary Permitting
Permitting in the Florida Keys is very tricky! There are [designated marine zones](https://floridakeys.noaa.gov/fknms_map/welcome.html) but to conduct any species collections in waters along the keys even outside of these zones requires a [NOAA National Marine Sanctuaries Permit Application](https://sanctuaries.noaa.gov/management/permits/). 

For questions regarding FKNMS permits, contact **Dr. Harrison Albert**:

- [ ] Email: harrison.albert@noaa.gov

- [ ] Phone: 786-243-6037 

It seemed like the permit application could be filled out with **Throughout sanctuary** checked in **Section C - Project Information Proposed location of activities:**, but after email correspondence with Dr. Harrison Albert, it seems like we may need to be more specific. Email thread copied below:

*March 4, 2024*
> Hello,

I am a first year PhD student at Northeastern University advised by Dr. Remy Gatins (CC’d here). We are planning fieldwork for July and are trying to gather information about collection sites and required permitting. 

Our plan is to collect Holacanthus angelfish for my research focused on the origins of divergence between the two species in the Tropical Western Atlantic: H. ciliaris and H. bermudensis. Ideally we will collect 10-15 individuals (of each species if possible) via scuba by spearing from three different locations along the Florida Keys. Currently we are planning to collect from Tavernier with Conch Republic Divers, Layton with the Keys Marine Laboratory, and Key West with Finz Dive Center. If our collections take place at sites outside of special sanctuary zones, how do you recommend we complete the NOAA National Marine Sanctuaries permit application?

Apologies for the lack of detail regarding specific collection site information. Please let me know if we should designate specific sampling zones/coordinates in order to move forward.

Thank you in advance for your help! Looking forward to hearing from you.

Cheers,
>Annabel

*March 12, 2024*
> Hello Annabel, 
>
>Thank you for your patience while I reviewed your FKNMS permitting email inquiry. 
>
>Unfortunately, this request is a bit complicated. At this time, I am not able to provide you with ONMS permit guidance until you are able to provide the FKNMS permits office with a SAL. Once / if you are able to obtain a SAL, I will also need to know the specific locations you are requesting to collect from (i.e., 4 GPS points that connect to create a polygon), especially if the collections will take place in Key Largo or Looe Key Existing Management Areas (which I would try to avoid conducting in for ease of permitting). 
>
>Please let me know once you obtain the SAL, or if FWC is able to provide you with information / guidance on whether this would be possible & issued in your requested timeline and we can proceed from there to apply for the ONMS permit. 
>
>All the best, 
>
>Dr. Harrison

** *Will continue updating after we hear back about our application! - Annabel 03/14/2024*
