## Otolith Processing

[Edit this page](https://github.com/remygatins/GatinsLab/edit/main/lab_gen_otoliths.qmd)


**Materials**

* 1-2 Otoliths (at least one with reading axis intact)

* 1 small and 1 large Weigh boat (for weighing and crystal bond)

- 2 0.5 mL microcentrifuge tubes 

- 1 with MilliQ

- 1 with paper label for storage

- Kim Wipes

- Forceps

- Pencil

- Crystal bond

- Scalpel

- Microscope slide

- Slide label

- Spacer for isomet saw blades

**Equipment**

- Balance (left of the -80 fridge)

- Hot plate (left of the -80 fridge)

- Buhler Isomet saw (Grabowski Lab)
	- The saw should have a piece of tape with a vertical line for aligning the core of the otolith with the gap in the saw. If not, directions for creating one are at the bottom of this protocol.

- Microscope and adapter for imaging (Vollmer lab)

- Lab laptop and hard drive for storing images (Above extra monitor in lab)

#Protocol Beginning

Ensure at least one otolith in the pair has an intact reading axis. When starting out, it is best to learn on  an otolith whose pair also has the reading axis intact, as otoliths can break during cutting.   

* Once you have identified the sulcus, the reading axis is perpendicular. Think of this as the sliver that will be removed from the center of the otolith. In this example, the reading axis follows the pink line

* The reading axis will not always run  through the very top and bottom of the otolith, just as the sulcus will not always run through the leftmost and rightmost points of the otolith
ADD PICTURE

1. Weigh both otoliths  
	a. If necessary, gently clean off any dried tissue from the both otoliths. It may be helpful to rehydrate the tissue with a wet kim wipe if there is a lot attached.

	b. Use a weigh boat to transfer the loose otoliths to the balance. Weigh them one at a time and record their masses in the sheet: https://docs.google.com/spreadsheets/d/1qRPYbAHzQ6yJ0N-8ua_G_tp_o3XYQdfXWglI8qzOcEg/edit?gid=0#gid=0.

	c. Replace the extra otolith in its storage plate.

2. Preparing the otolith for mounting.
	a. Put the otolith for processing in the 0.5 mL tube of MilliQ and set a timer for 10 minutes.

	b. While the otolith soaks:
		i. Preheat the hot plate to 110ºC

		ii. Use the scalpel to gently flake off chunks of Crystal bond. They do not need to be large! Just enough to fully embed the 	otolith.

		iii. Place the blank slide on the hot plate. Leave a third of the slide hanging off so you can easily pick up the slide without burning your fingers.

		iv. Put a small amount of crystal bond flakes on the left third of the slide. Do not put it in the center, as this makes it 	difficult to properly mount the slide on the saw.
ADD PICTURE

		v. Make the labels. Cut out the paper label for storage and write out the sticker for the slide.

	c. after soaking the otolith, gently dry it off and place on a dark surface. Locate the core of the otolith and the sulcus. Using 	the pencil, gently sketch a line on the top of the otolith perpendicular to the sulcus and through the core. It doesn’t matter 		which side the pencil mark is on.
ADD PICTURE

3. Mount the otolith. Gently place the otolith on the melted crystal bond with the pencil side up. The line should be perpendicular to the long side of the slide (so the sulcus should run the same direction as the long side). With the slide on the hot plate, use forceps to gently move the crystal bond over the top of the otolith to ensure it is fully encased.
ADD PICTURE

4. Allow to cool before proceeding to cut.

#Cutting the otolith

The saw should have a mark on it to line up the mounted otolith for cutting. If not, you can use a squared slide with tape to mark where the blades will cut.
ADD PICTURE

1. Set up the saw for cutting. The correct order is flange, blade, spacer, blade, flange. Tighten.
	a. Use the larger flanges. The default spacer for holacanthus otoliths is the nut stored with the saw, but feel free to experiment with different spacer widths as needed.

	b. Fill the basin with water and a few drops of soap. This does not need to be replaced more than once a week.

2. Remove the mounting block from the saw and place it upside down against the tape. Insert the slide with the otolith facing up and align the pencil mark on the sulcus with the mark on the tape. Everything should be oriented so that when the block is on the saw, the otolith is first to hit the blade.

3. Gently tighten the mounting block. Make sure the slide doesn’t wiggle in the mount, but do not over tighten as this risks cracking the glass.

4. Stack the weights on the back of the saw. We use two medium weights (~100 g) but feel free to experiment.

5. Turn on the saw. Set to a low speed (between 3 and 5).

6. Slowly lower the cutting arm to the blade. Do not press down. Listen closely to the sound as there is a distinct noise when the saw cuts glass.
	- If the otolith piece falls out during cutting, immediately turn off the saw. Look between the blades to try and see the otolith and scoop it out. You can then stick a curved piece of plastic in between the blades and run the saw at speed 1 for a whole revolution. If the otolith piece does not come out, then it is time to take everything apart and start searching the water bath.

	- Sometimes the otolith breaks during cutting and there are no salvageable parts. If this happens, make sure to scour the well and remove any pieces before cutting any more otoliths (so you don’t mix up otolith parts)

7. Once the otolith is cut, gently reheat the crystal bond to remove the slice. Do not attempt to pry it out as this can damage the otolith.

8. Store the otolith in a 0.5 mL tube or mount onto a slide using crystal bond with the cut side up
	- Before mounting, inspect both sides of the cross section to determine which one is better for reading. Mount this side up. If the crystal bond obscures the cross section after mounting, gently sand using wet 600 grit sandpaper then polish with 1 micron lapping film.

#Imaging the Otolith

This protocol specifically refers to the compound microscope in the former Vollmer lab. Speak to Angela for hands-on directions.

The software used for the camera, ToupView, is already downloaded on the lab laptop. It is available for download here: https://www.microscope.com/software-downloads. Angela recommends downloading an older version of the software (2017) as newer versions may not be compatible with the camera.

1. Turn on the power for the camera and the light box. 

2. Push in/pull out the switch at the top of the microscope so the FOV is visible through the eyepieces

3. Bring the lines of the otolith into focus. ToupLite tends to zoom in the image compared to the eyepieces, so I recommend staying on 2x.

4. Open ToupView and plug in the camera. Change the position of the lever so the image appears on the screen.

5. Navigate to options > preferences or use control + P to open the preferences dialogue. Rename the file prefix with the otolith ID.

6. After refocusing, click the snap button or use control + Q (quick save) to take pictures of the otolith.
	- Once images are taken, they can be transferred to the hard drive for editing and enumerating

	- If necessary, otolith images can be edited using Adobe lightroom (available through Northeastern) or any preferred software.

7. Enumerate the otolith using ImageJ and upload the count to the spreadsheet. Each otolith should be counted multiple times with at least a week between then.
