# Qiagen DNeasy extraction

**(using Qiagen blood and tissue kit)**

[Edit this Page](https://github.com/remygatins/GatinsLabProtocols/blob/main/lab_molec_dnaextraction.qmd)

Protocol adapted from [Lotterhos lab protocol](https://drk-lo.github.io/lotterhoslabprotocols/molecprot_dnaextractionqiagen.html), [DNeasy® Blood & Tissue Kit (Quick-Start Protocol April 2016)](https://www.qiagen.com/us/resources/resourcedetail?id=aa250d94-fc4b-4e27-bb74-d32391ff8a48&lang=en), & [DNeasy Blood & Tissue Handbook](https://www.qiagen.com/us/resources/resourcedetail?id=68f29296-5a9f-40fa-8b3d-1c148d0b3030&lang=en)

## Tissue Lysing

**Need:**

- [ ] scale
- [ ] sterile forcepts (store in 50 ml tube with 10% bleach then rinse with DI water spray bottle over waste container OR spray with 70% EtoH and use a flame to burn off any residual EtoH and tissue.)
- [ ] scalpel or razer (clean between samples with same steps as forcepts)
- [ ] weighting boats
- [ ] 1 ml tubes
- [ ] ice container
- [ ] [Qiagen blood and tissue kit](https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/dneasy-blood-and-tissue-kit?catno=69506) 
  - [ ] Buffer ATL (if there are precipitates heat at 56 C and mix gently)
  - [ ] Proteinase K

**Steps:**

- [ ] 1. preheat thermomixer to 56 °C
- [ ] 2. clean area with 10% bleach, water, then 70% ethanol
- [ ] 3. prep ice container to store tissue samples while working
- [ ] 4. remove tissue samples from freezer and let thaw; once thawed place on ic
- [ ] 5. while waiting for samples to thaw
  - [ ] 5.1. label 1 ml tubes
  - [ ] 5.2. add 180 µl of Buffer ATL & 20 µl of Proteinase K into labeled 1 ml tubes
- [ ] 6. tare weighing boat on scale
- [ ] 7. carefully remove tissue from storage tube with forcepts and use sterile blade to cut a piece of tissue roughly 20mg in weight. Using 100% EtoH, gently rinse tissue and pat dry with clean kim wipe, so that the tissue appears nearly dry
- [ ] 8. plase tissue on weighing boat and measure weight (should weigh around 20mg +/-2mg, if not remove or add tissue as nessesary) 
- [ ] 9. once correct weight, place tissue in prepped 1 ml tube
- [ ] 10. record weight in lab notebook
- [ ] 11. seal tube and store on ice until all samples are complete
- [ ] 12. clean instruments between each tissue sample by soaking in 10% bleach, spraying with DI water (holding over waste container/glassware), then wiping down with kimwipe. (could also sterilize with DI water, 70% ethanol, then then running instrument through an ethanol lamp filled with 100% ethanol)
- [ ] 13. repeat steps 5 through 11 for every sample
- [ ] 14. confirm that all tubes are sealed, then vortex for 15 seconds
- [ ] 15. place samples on thermo-mixer set at 56 °C at 600 rpm (check after 2 mins to make sure everything is sealed)
- [ ] 16. samples can be left for at least 2 hours or overnight to allow for all tissue to be completely lysed

## DNA extraction

**Need:**

- [ ] 96-100% molecular grade ethanol
- [ ] [Qiagen blood and tissue kit](https://www.qiagen.com/us/products/discovery-and-translational-research/dna-rna-purification/dna-purification/genomic-dna/dneasy-blood-and-tissue-kit?catno=69506)
  - [ ] DNeasy spin columns
  - [ ] DNeasy collection tubes
  - [ ] Buffer AL
  - [ ] Buffer AW1
  - [ ] Buffer AW2
- [ ] 1.5 or 2 ml microcentrifuge tubes (for final storage)
- [ ] warmed 1X low TE buffer (37ºC); may need to make by diluting [20X low TE buffer](https://remygatins.github.io/GatinsLabProtocols/lab_molec_low_te_buffer.html)

**Steps:**

- [ ] 1. prep and clean bench with 10% bleach, water, then 70% ethanol
- [ ] 2. label spin-column tubes and final storage tubes
- [ ] 3. remove samples from thermo-mixer
- [ ] 4. add 200 μl Buffer AL to samples, then vortex
- [ ] 5. add 200 μl Ethanol (96-100% molecular grade) to samples, then vortex
  - Note: A working solution of Buffer AL & ethanol can be made to be aliquoted into sample tubes.
- [ ] 6. pipet the mixture into a DNeasy Mini spin column placed in a 2 ml collection tube
- [ ] 7. centrifuge for 1 min at ≥ 6000 x g (8000 rpm)
- [ ] 8. change gloves after each centrifuge step
- [ ] 9. discard the flow-through & collection tube
- [ ] 10. tranfer spin column to a new collection tube
- [ ] 11. pipet 500 μl Buffer AW1 into the spin column
- [ ] 12. centrifuge for 1 min at ≥6000 x g (8000 rpm)
- [ ] 13. discard the flow-through & collection tube
- [ ] 14. tranfer spin column to a new collection tube
- [ ] 15. pipet 500 μl Buffer AW2 into the spin column
- [ ] 16. centrifuge for 3 min at 20,000 x g (14,000 rpm)
- [ ] 17. discard flow through, place back into collection tube, & spin again for 1 more min
- [ ] 18. make sure all the spin column membranes are dry after this step; spin again for 1 min if not
- [ ] 19. discard the flow-through & collection tube
- [ ] 20. tranfer spin column to a new 1.5 ml or 2 ml microcentrifuge tube (for final storage)
- [ ] 21. elute the DNA
  - [ ] 21.1. if only eluting once: 
    - [ ] add 100 μl of warm low TE buffer (warm in thermomixer, 37ºC) to the center of the spin column membrane 
    - [ ] incubate for 1 min at room temperature (15–25°C) then centrifuge for 1 min at ≥6000 x g (8000 rpm)
  - [ ] 21.2. if eluting twice (to increase yeild):
    - [ ] add 100 μl of warm low TE buffer (warm in thermomixer, 37ºC) to the center of the spin column membrane 
    - [ ] incubate for 1 min at room temperature (15–25°C) then centrifuge for 1 min at ≥6000 x g (8000 rpm)
    - [ ] transfer spin column to a new 1.5 ml or 2 ml microcentrifuge tube (label tube differently than the first to note that it has the second elution in it) 
    - [ ] add another 100 μl warm low TE buffer
    - [ ] incubate for 1 min at room temperature (15–25°C)
    - [ ] centrifuge for 1 min at ≥6000 x g (8000 rpm)
- [ ] 22. store in fridge for a few days or freeze at -20 or -80 if not using immediately 

## Possible Next Steps 

- [Qubit](https://remygatins.github.io/GatinsLabProtocols/lab_equip_qubit.html)
- PCR then [gel electrophoresis](https://remygatins.github.io/GatinsLabProtocols/lab_molec_gel_electrophoresis.html)
