# 20x Low TE Buffer
[Edit this page](https://github.com/remygatins/GatinsLab/edit/main/low_te_buffer.qmd)

## Materials
- [ ] Tris base
- [ ] EDTA (Ethylenediamine Tetraacetic Acid, Disodium Salt Dihydrate)
- [ ] HCL
- [ ] DI water
- [ ] stir bar

## Equipment
- [ ] magnetic stir plate
- [ ] pH meter


## Protocol
1.
- Measure out 800 ml deionized water into a graduated cylinder.
- Tranfer to large (1000 ml) erlenmeyer flask

2. 
- Add 24.22g Tris Base
- Add 0.584g EDTA

3. 
- Add magnetic stir bar
- Mix for 5 mins at 300 rpm on magnetic stir plate

4.
- Set up magnetic stir plate and pH meter in fume hood
- Calibrate pH meter if it hasn't been calibrated recently
  - Use 2-3 pH standards, find directions for calibration elsewhere, might be a good thing to add
  - **Keep pH meter in a liquid always! Do not let probe dry out!**

5. 
- Keep mixture mixing on magnetic stir plate at 300rpm
- Put the pH meter's probe into mixture
- Slowly add quantities of HCl, checking pH as you go, until pH is 8.0
  - As pH lowers, more HCl will be required to continue to lower it since pH is a log scale
  - Last time it took 10.5mL amount of HCl, I recommend doing 1000 uL increment amounts to start and then do less as you get closer to 8.0
  - **Do not go under pH 8.0** :( idk how to bring it back up

6. 
- Bring volume to 1L with DI water

7.
- Tranfer mixture into a long-term autoclave-safe storage container

8.
- Autoclave for 50 min with cap tightened to a single turn
- Store
