# Interviews

[Edit This Page](https://github.com/remygatins/GatinsLabProtocols/blob/main/prof_development_interviews.qmd)

## Job

### Preparing for interviews

### Questions for interviewers

## Grad School

### Preparing for interviews

### Potential Questions

- [Graduate School Interview Question Bank(BEACHES 2024)](https://docs.google.com/document/d/1FKBudWBaPcQegXT_L1pznewoiOxLKmvut98dJRgZ4nY/edit?usp=sharing)
  - RESEARCH INTERESTS
    - Tell me about yourself. Why are you interested in graduate school? 
    - Do you have any past research experience? What parts of it did you like and which did you not like?
    - Why do you think my lab is a good fit?
    - Are you familiar with my research? What interested you the most?
    - Which 3-5 of my papers did you select to read? Which did you like the most? (This question is less common but some advisors have specific expectations for you when you         interview. If they ask this, they likely will inform prospective students to prepare for this question beforehand)
    - Why did you choose Northeastern University to pursue graduate school?
    - What is one major objective you hope to achieve as a graduate student?
    - What experience do you have that makes you think you are ready to tackle graduate school?
    - Let’s say you had all the money in the world, if you could test any question for your Masters/PhD, what would you test?
    - What do you foresee as the long-term or broad implications of your research? What impact do you want your PhD to have and why?
    - Tell me about a research publication that you read recently and why you found it interesting.
    - For a PhD position: A PhD is a challenging degree, why is it the right choice for you to pursue? (Why do you want a PhD and not another degree, ex. research M.S.?)
  - CAREER/AFTER GRAD SCHOOL
    - Are you interested in a career in academia or elsewhere (industry, social justice/advocacy, teaching, etc)?
    - If you did not pursue graduate school, what career path would you choose? 
  - HOW DO YOU WORK
    - What would you say are your strengths? 
    - What would you say are your weaknesses?
    - Meeting deadlines is an important part of being a good scientist. Can you give me some examples of how you plan out a project so you can meet the deadline?
    - In grad school, you have to balance teaching, lab, field, etc. How do you stay organized? 
    - When you find out about an event, do you add it to your calendar right away?
    - If you’re having difficulty having a particular problem, walk me through the process of how you approach a problem that you’re having difficulty solving 
    - Give me an example (and check if their example matches the process they describe)
    - Can you give me an example of a time that you needed outside expertise with a problem, and how you found that expertise?
    - Can you give me an example of how you had to be a leader and some of the decisions you had to make? 
    - In science, we experience far more criticism than compliments. Give an example of a time you were criticized for a mistake, and how you responded?
    - Do you prefer to work in a team environment or individually, and why?
    - How do you deal with uncertainty and challenges?
    - What qualities are you seeking in a mentor? 
    - Do you prefer to work with a mentor that is hands on or hands off?
  - SKILLS
    - Do you keep a lab notebook? How often do you write in it, and what kind of information do you think is important to keep in a notebook?
    - What unique skills, perspective, or experience are you bringing to contribute to the lab as a whole? How do you envision contributing to the diversity of the lab?
    - Do you have any lab or fieldwork experience? If so, describe any unique skills you have gained from them.
    - What was one instance where you made a mistake and how did you attempt to fix it? Or at least make sure it did not happen again
    - Do you have any experience with teaching, tutoring, or mentoring? If so, describe that experience and what you enjoyed about it. 
    - What do you anticipate will be the most challenging aspect of graduate school for you and why?
    - Collaborations and communication are also important. Have you ever dealt with a situation where people have miscommunicated with each other and how did you deal with it?
    - What do you think is your greatest academic accomplishment?
  - GENERAL QUESTIONS
    - What is a personal interest or hobby and how do you maintain work/life balance?
    - Do you have any questions for me? (Candidates should always have a question or two on hand and ready for this)
    - What are other schools and advisors you’re interested in working with for your graduate career?

### Questions for interviewers

