# Onboarding
[Edit this page](https://github.com/remygatins/GatinsLabProtocols/edit/main/welcome_onboarding.qmd)

## General access to lab resources
- [ ] Ask Dr. Gatins to add you to our Lab Slack Channel
- [ ] Share your email with Dr. Gatins to gain access to our Google Drive. This will give you editing access to:
    - the lab webpage, where you can add yourself to the People page
    - A shared lab resources folder
    - The Gatins Lab calendar
- [ ] Create a GitHub account (if you don't have one already) and ask me to add you as a collaborator to this protocols page
- [ ] Add your contact information to the [Gatins Lab Contact information sheet](https://docs.google.com/spreadsheets/d/1F0nNCh9XOA6ftbaqpWzlNunnv5DYv7lUeQRbHXoanlk/edit#gid=0) 
- [ ] Add your photo to the lab board! Link to profile template [here](https://www.canva.com/design/DAF6ukfdlcA/64Soj04BBS37ls7ZPvtQlA/view?utm_content=DAF6ukfdlcA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview).

## General MSC requirements
*Navigate to the [Gatins Lab Onboarding Docs](https://drive.google.com/drive/u/0/folders/1RO_sHPwa3eDx0-oPS0HqBablwW_Gx5R4) to find all the documents listed below*  

- [ ] Fill out the [Intake form](https://docs.google.com/forms/d/e/1FAIpQLSeRMAg-o4vpdjGcVK-HBbFxNBGn3mARwnBbX9F4UOrTeDf9nQ/viewform) for the MSC
- [ ] Read the **Lab Safety Plan** and electronically sign the **Lab Safety Agreement** and **Lab Access Waiver**, these forms should be sent to [Ryan Hill](mailto:r.hill@northeastern.edu), and CC Dr. Gatins as well.

## MSC Setup
- [ ] Email [Ryan Hill](mailto:r.hill@northeastern.edu) about getting ID card access to campus facilities, including the main Edwards building, the bunker, and the lab (Edwards 134).
- [ ] In order to print at the MSC, you can connect to each printer using its unique IP address:

B&W Printer - Grad Trailer - 10.30.13.247
Color Printer - Faculty Hallway - 10.30.13.248
B&W Printer - Faculty Hallway - 10.30.13.249


## Molecular lab
- [ ] Ask Dr. Gatins to add you to the Gatins Lab group on SciSchield (BioRaft)

Complete the following trainings on SciSchield:  

- [ ] Laboratory Safety Program Orientation
- [ ] Fundamentals of Laboratory Safety
- [ ] Hazardous Waste Training
- [ ] Biosafety Training
- [ ] Cryogenic Liquids
- [ ] Regulated Medical Waste
- [ ] any other training specific to your work

Contact [Rosie](mailto:r.falco@northeastern.edu) from the **Ocean Genome Legacy Center** to schedule the following trainings:  

- [ ] Shared Equipment Training
- [ ] Autoclave
- [ ] Cryogeneics (Liquid Nitrogen)

## IACUC
Complete the following Institutional Animal Care and Use Committee (IACUC) tasks:

- [ ] Ask Dr. Gatins to add you to the Institutional Animal Care and Use Committee (IACUC) Animal Care and Use protocol. 
- [ ] Complete the Animal Contact Questionnare and send the form with your immunization records to Erin Credle (e.credle@northeastern.edu).
- [ ] Review the Division of Laboratory Animal Medicine (DLAM) & IACUC Training Course on Canvas
- [ ] Take the "Assessment Quiz for Working with Rodents"


## Northeastern Explorer Cluster
- [ ] if you will be running analyses on Northeastern's Explorer High Performance Cluster (HPC) you first need to submit an access request [here](https://service.northeastern.edu/tech?id=sc_cat_item&sys_id=0ae24596db535fc075892f17d496199c)
        - Add your NU email to populate the requester information
        - University sponsor: r.gatins@northeastern.edu
        - Gaussian: No
- [ ] Let Dr. Gatins know once you have been approved so she can add you to our shared folder on the cluster (/projects/gatins)
- [ ] If you need to backup data request access to the Synology NAS system below

## Synology NAS
- [ ] Ask Dr. Gatins to add you to our lab Synology using your personal email
- [ ] Once you are added, follow the detailed instructions of our [Synology NAS](https://remygatins.github.io/GatinsLabProtocols/coding_synology.html) to create a folder project and use the Synology
 
